### ISSUE TITLE
Shared data is not updated from scratch extension to microbit

### ISSUE THREAD

**Issue by virivigio** [yokobond/pxt-scratch-microbit-more#2]
**Describe the bug**
If I set shareddata0 to 1 in scratch extension microbit still sees 0

**To Reproduce**
1. create a scratch project in https://yokobond.github.io/scratch-microbit-more/
2. put two actions in it. one to check that the link is working and another one to modify shared data
![Schermata 2020-05-26 alle 15 37 23](https://user-images.githubusercontent.com/1875906/82907402-dc510800-9f66-11ea-95a0-b3158a127075.png)

3. go to https://github.com/yokobond/pxt-scratch-microbit-more/releases/tag/v0.4.1
4. go to https://makecode.microbit.org/_0mA8sEdvY3a1
5. click on modify to edit the project in makecode full ide
6. modify the project as in this image
![Schermata 2020-05-26 alle 15 34 29](https://user-images.githubusercontent.com/1875906/82907060-6c428200-9f66-11ea-99b8-2f9f0445d7a5.png)

7. deploy to microbit and start it
8. connect scratch with scratch link (everything looks fine)
9. on start we see "0" on microbit (and this is what we expected)
10. double click the "heart" on scratch, there is a quick blink in microbit (again this is expected, we draw the shape but then we draw again number zero)
11. double click the set shared data on scratch
12. scratch says 1, microbit still shows zero
![WhatsApp Image 2020-05-26 at 15 39 22](https://user-images.githubusercontent.com/1875906/82907616-21753a00-9f67-11ea-8b74-1c80f5e060e7.jpeg)

**Configuration of hardware**
Hardware which connected to micro:bit.
- USB & bluetooth
- Connected things on the pins: it is reproducible without any pin connected

**Expected behavior**
I expected to see 1

**Scratch (please complete the following information):**
 - MacOS HighSierra on MacBook Pro
 - Chrome 81.0.4044.138
- Scratch Link 1.3.0
 - Version: we used online version https://yokobond.github.io/scratch-microbit-more/ and https://github.com/yokobond/pxt-scratch-microbit-more/releases/tag/v0.4.1

**Comment by virivigio** [comment]
As a side note, since I remebered I gave slots (this was the name) a try in the past:
- microbit with version 0.3.2
- scratch with https://github.com/yokobond/scratch-vm/blob/extension/microbit-more/src/extensions/scratch3_microbit_more/index.js

and today I replicated the test with those versions (locally) and it worked as expected
![WhatsApp Image 2020-05-26 at 16 18 22](https://user-images.githubusercontent.com/1875906/82912790-c6931100-9f6d-11ea-890c-95e7f4e76f06.jpeg)

**Comment by yokobond** [comment]
Thank you for your detailed reports. 
I found bugs in both yokobond/pxt-scratch-microbit-more and yokobond/scratch-microbit-more .
I will fix them to work shared data.

**Comment by yokobond** [comment]
Fix this on 377e9cae38baa7c343cc2e3bc71985008775e2fe and  yokobond/scratch-microbit-more@c7eedc2b6b7c2f5399b19d418214f5a0b3db5a17 .
