### ISSUE TITLE
Cann't compile pxt-scratch-microbit-more-v0.5.0

### ISSUE THREAD

**Issue by marron9999** [yokobond/pxt-scratch-microbit-more#7]
Open url: https://makecode.microbit.org/_iXhFjt5b3gdJ
and, move to Editor
and, download to micro:bit
but, occurs compile error !

Chrome debug console:

   :

webusb: get devices
editor.js:2415 Connecting...
editor.js:2446 Connected
pxtapp.js:2293 polling C++ build https://makecode.com/compile/98353773806574fddb3fc197572dc36a17d9be7914e4ee125939ee2e46042732.json
pxtapp.js:2293 build log https://makecode.com/compile/98353773806574fddb3fc197572dc36a17d9be7914e4ee125939ee2e46042732.log
pxtapp.js:2293 build failed
pxtapp.js:2293 Cloning into '/home/build/prjclone'...
Note: checking out '2c38d7458e5f4265451af5e6317582494bc18515'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Creating libraries folder
Cloning into: https://github.com/lancaster-university/codal-microbit-v2
Cloning into 'codal-microbit-v2'...
Checking out branch: v0.2.24
HEAD is now at 6602716... Snapshot v0.2.24
[1;35mSet target: codal-microbit-v2 [m
[1;35mUsing target-locked.json[m
[1;34mTargeting codal-microbit-v2[m
Installing dependencies...
Cloning into: https://github.com/lancaster-university/codal-core
Cloning into 'codal-core'...
Checking out branch: 969813d451c33daeccef3b41cf904f6c08e6974f
HEAD is now at 969813d... Merge branch 'master' of https://github.com/lancaster-university/codal-core
Cloning into: https://github.com/lancaster-university/codal-nrf52
Cloning into 'codal-nrf52'...
Cloning into 'nrfx'...
Checking out branch: 1a8624801d45301e0f5dfc2c1a17a5efca8082ab
HEAD is now at 1a86248... Support zero length NRF52I2C write transactions
Cloning into: https://github.com/microbit-foundation/codal-microbit-nrf5sdk
Cloning into 'codal-microbit-nrf5sdk'...
Checking out branch: 691869a8261e08b283deb0e2267fae3c00c17dae
HEAD is now at 691869a... Merge pull request #11 from martinwork/saving-flash
[1;32mUsing library: codal-microbit-v2[m
[1;32mUsing library: codal-core[m
[1;32mUsing library: codal-nrf52[m
[1;32mUsing library: codal-microbit-nrf5sdk[m
/tmp/ccIB9nBI.s: Assembler messages:
/tmp/ccIB9nBI.s:110: Warning: ignoring changed section attributes for .data
In file included from /home/build/prjclone/libraries/codal-microbit-v2/inc/MicroBitConfig.h:5:0,
                 from /home/build/prjclone/libraries/codal-microbit-v2/inc/MicroBitDevice.h:30,
                 from /home/build/prjclone/libraries/codal-microbit-v2/source/MicroBitAccelerometer.cpp:31:
/home/build/prjclone/libraries/codal-microbit-v2/inc/compat/yotta_cfg_mappings.h:91:0: warning: "MICROBIT_STACK_SIZE" redefined
     #define MICROBIT_STACK_SIZE YOTTA_CFG_MICROBIT_DAL_STACK_SIZE
 
    :

 
In file included from /home/build/prjclone/libraries/codal-microbit-v2/inc/MicroBitConfig.h:5:0,
                 from /home/build/prjclone/libraries/codal-microbit-v2/source/MicroBitDevice.cpp:25:
/home/build/prjclone/libraries/codal-microbit-v2/i
pxtapp.js:2297 TypeError: Cannot read property 'length' of null
    at compressHex (https://pxt.azureedge.net/blob/19cf1a4a623d9d6913ec0669b326e18824ddbee1/pxtapp.js:5657:37)
    at https://pxt.azureedge.net/blob/19cf1a4a623d9d6913ec0669b326e18824ddbee1/pxtapp.js:5586:36
From previous event:
    at https://pxt.azureedge.net/blob/19cf1a4a623d9d6913ec0669b326e18824ddbee1/pxtapp.js:5584:26
From previous event:
    at Object.getHexInfoAsync (https://pxt.azureedge.net/blob/19cf1a4a623d9d6913ec0669b326e18824ddbee1/pxtapp.js:5566:18)
    at Host.getHexInfoAsync (https://pxt.azureedge.net/blob/37e3fd85a6337e2722f769e16a60f74c54d64465/main.js:27976:30)
    at MainPackage.<anonymous> (https://pxt.azureedge.net/blob/19cf1a4a623d9d6913ec0669b326e18824ddbee1/pxtapp.js:11643:78)
    at step (https://pxt.azureedge.net/blob/19cf1a4a623d9d6913ec0669b326e18824ddbee1/pxtapp.js:48:23)
    at Object.next (https://pxt.azureedge.net/blob/19cf1a4a623d9d6913ec0669b326e18824ddbee1/pxtapp.js:29:53)
    at https://pxt.azureedge.net/blob/19cf1a4a623d9d6913ec0669b326e18824ddbee1/pxtapp.js:23:71

    :

{sha: "98353773806574fddb3fc197572dc36a17d9be7914e4ee125939ee2e46042732"}sha: "98353773806574fddb3fc197572dc36a17d9be7914e4ee125939ee2e46042732"__proto__: Object
pxtapp.js:2293 error: main.ts(1,1): error TS9200: Cannot read property 'hex' of null

pxtapp.js:2293 warning: コンパイルが失敗しました。エラーコードを確認してください。

**Comment by yokobond** [comment]
Thank you for your report. 
This project moved to a new repository [yokobond/pxt-mbit-more-v2](https://github.com/yokobond/pxt-mbit-more-v2). That new version will be compiled on MakeCode.
